# Generated by Django 5.0.2 on 2024-02-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses_app', '0002_initial'),
        ('custom_user_app', '0003_alter_user_managers_alter_user_email'),
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
