version: '3'

services:
  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
  web:
    build: .
    command: >
      sh -c "npm run build &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=messenger_project.settings_docker
  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A messenger_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis


  celery-beat:
    build: .
    command: celery -A messenger_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=messenger_project.settings_docker
  db:
    image: postgres
    environment:
      POSTGRES_DB: messenger_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345


