# Generated by Django 5.0.2 on 2024-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
