# Generated by Django 5.0.2 on 2024-03-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_remove_participants', 'Can remove participants from chat')]},
        ),
    ]
