# Generated by Django 5.0.2 on 2024-03-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chat_options_alter_chat_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_change_chat', 'Can change chat permissions'), ('can_create_chat', 'Can create chat permissions')]},
        ),
    ]
