# Generated by Django 5.0.2 on 2024-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_to_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
            ],
        ),
    ]
