# Generated by Django 5.0.2 on 2024-03-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_userstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='last_login',
            new_name='last_activity',
        ),
    ]
