# Generated by Django 5.0.1 on 2024-02-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_rename_category_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
