# Generated by Django 5.0.1 on 2024-02-18 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_rename_name_course_title'),
        ('members_app', '0002_userenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(through='members_app.UserEnrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
